config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#top"
  get "/top" => "home#top"
  get "/login" =>"home#login"

  #resources :categories
    #categoriesは管理者しか更新しないのでviewやアクションの定義の必要なし
    ##
    
  resources :habit_records, only: [:update]
    #habit_recordsのindex（habitごとのhabit_recordsの記録）はhabitのshowアクションで表示する。
  resources :users,  except: [:index]
    # indexはいらない（ユーザー一覧ののページは必要なし）
  resources :projects, except: [:new]
  get "/closed_projects" => "projects#closed"
    # "/projects"上の＋ボタンで新しいプロジェクトを作るのでnewは不要。

  resources :project_todos, only: [:create, :update, :destroy]
    # viewはいらない。管理者のみがが閲覧できればOK.
  resources :todos, except: [:new]
    # "/projects"や"/habits"上のボタンで新しいtodoを作るのでnewは不要。
  resources :habits, except: [:new]
  get "/habituation" => "habits#habituation"
    # "/habits"上の＋ボタンで新しいプロジェクトを作るのでnewは不要。


  # これを見ながらルーティングしてます。
  # https://pikawaka.com/rails/resources

  # resources　:tweetsの場合
  # get 'tweets'     => 'tweets#index'
  # get 'tweets/:id' => 'tweets#show'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id/edit' => 'tweets#edit'
  # patch 'tweets/:id'  => 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'

  # 一部だけ使うときはonlyをつける。 ex.resources :users, only: [:edit, :new]
  # 一部だけ使わないときはexceptをつける。 ex.resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :todos
end

app/models/habit.rb
class Habit < ApplicationRecord
	has_many :habit_records
	belongs_to :user
end

app/models/habit_history.rb
class HabitHistory < ApplicationRecord
end

app/models/habit_record.rb
class HabitRecord < ApplicationRecord
	belongs_to :habit
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :todos, through: :project_todos
	has_many :project_todos
end

app/models/project_todo.rb
class ProjectTodo < ApplicationRecord
	belongs_to :project
	belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user
	has_many :project_todos
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :first_name, {presence: true}
	validates :last_name, {presence: true}
	validates :user_name, {presence: true, uniqueness: true}
	validates :mail, {presence: true, uniqueness: true}


	has_many :habits
	has_many :projects
	has_many :todos


end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def closed
  end
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:user_id, :personal_project_id, :project)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:user_id, :personal_todo_id, :todo, :deadline, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	render :layout  => nil
  end

  def create
  	@user = User.new(
  		first_name: params[:first_name], 
  		last_name: params[:last_name],
  		user_name: params[:user_name],
  		mail: params[:mail],
  		password: params[:password])
  	@user.save
  	redirect_to("/top")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/habit_records_helper.rb
module HabitRecordsHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :personal_project_id %>
    <%= form.text_field :personal_project_id %>
  </div>

  <div class="field">
    <%= form.label :project %>
    <%= form.text_field :project %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/closed.html.erb
closedしたprojectsを表示するページ

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<body>
    <!-- colum -->
    <main role="main" class="col-md-10 ml-sm-auto col-lg-10 px-4">

      <!-- title & btn -->
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">YOUR WORK</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary" id="add_btn">＋</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">ー</button>
          </div>
          <div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span data-feather="calendar"></span>
              HISTORY
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Last 7 days</a>
              <a class="dropdown-item" href="#">Last 2 week</a>
              <a class="dropdown-item" href="#">Last month</a>
            </div>
          </div>
        </div>
        </div>

      <!-- task card -->
      <div class=row id="main_menu">
      <!-- 一旦user_idを手打ちで設定 -->
        <% @projects.where(user_id: 1).ids.each do |project_id| %>
          <!-- No.1 -->
          <div class="col-lg-4 col-md-6 my-2" id="card1">
            <div class="card" style="background-color:#fff">
              <div class="card-header py-2">
                <span style="font-size:16pt"><%= @projects.find(project_id).project %></span>
                <span class="float-right" style="font-size:16pt">MM/dd</span>
              </div>
              <!-- table -->
              <div class="card-body py-0">
                <table class="table table-borderless table-hover">
                <thead>
                  <tr>
                  <th scope="col">TODO</th>
                  <th scope="col">Deadline</th>
                  <th scope="col">Done</th>
                  </tr>
                </thead>
                <tbody>
                  <% Todo.where(project_id: project_id).each do |todo| %>
                    <tr>
                    <th scope="row"><%= todo.todo_content %></th>
                    <td><%= todo.deadline %></td>
                    <td>  <div class="form-group form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1" style="transform:scale(2.0)">
                    </div></td>
                    </tr>
                    <% end %>
                </tbody>
                </table>
              </div>
              <div class="card-footer">
                <!-- btn -->
                <div class="btn-group mr-2 float-right">
                  <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#testModal1" id="workButton1">edit</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#testModal2" id="workButton2">delete</button>
                </div>
                <!-- edit -->
                <div class="modal fade" id="testModal1" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">project title</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                  <div class="modal-body">
                    <label>tasks</label>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">save</button>
                  </div>
                  </div>
                  </div>
                </div>
                <!-- delete -->
                <div class="modal fade" id="testModal2" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-body">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <label>Would you delete this task?</label>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                        <button type="button" class="btn btn-danger"  id="delete_btn">Yes</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </main>
  </div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="js/app.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- add card -->
    <script>
      $(function() {
        $("#add_btn").click(function() {
          $("#main_menu").append(            `
          <div class="col-lg-4 col-md-6 my-2" id="card1">
          <div class="card" style="background-color:#fff">
            <div class="card-header py-2">
            <span style="font-size:16pt">Title of your task</span>
            <span class="float-right" style="font-size:16pt">MM/dd</span>
          </div>
          <div class="card-body py-0">
            <table class="table table-borderless table-hover">
            <thead>
              <tr>
              <th scope="col">TODO</th>
              <th scope="col">Deadline</th>
              <th scope="col">Done</th>
              </tr>
            </thead>
            <tbody>
              <tr>
              <th scope="row">Biz session</th>
              <td>10/05</td>
              <td>  <div class="form-group form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1" style="transform:scale(2.0)">
              </div></td>
              </tr>
              <tr>
              <th scope="row">Business report</th>
              <td>10/15</td>
              <td>  <div class="form-group form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1" style="transform:scale(2.0)">
              </div></td>
              </tr>
              <tr>
              <th scope="row">anual meeting</th>
              <td>10/25</td>
              <td>  <div class="form-group form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1" style="transform:scale(2.0)">
              </div></td>
              </tr>
            </tbody>
            </table>
          </div>
          <div class="card-footer">
            <!-- btn -->
            <div class="btn-group mr-2 float-right">
              <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#testModal1" id="workButton1">edit</button>
              <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#testModal2" id="workButton2">delete</button>
            </div>
            <!-- edit -->
            <div class="modal fade" id="testModal1" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">project title</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
              <div class="modal-body">
                <label>tasks</label>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">save</button>
              </div>
              </div>
              </div>
            </div>
            <!-- delete -->
            <div class="modal fade" id="testModal2" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <label>Would you delete this task?</label>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-danger"  id="delete_btn">Yes</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        `);
        });
      });
    </script>
    <!-- remove card -->
    <script>
      $(function(){
        $("#delete_btn").on("click", function(){
        $('#testModal2').modal('hide');
        $("#card1").remove();
        });
      });
    </script>
    <!-- checkbox -->
    <script>
      $(":checkbox").click(function() {
      if ($(this).is(":checked")){
        $(this).closest("tr").css("text-decoration", "line-through");
      }
      else {
        $(this).closest("tr").css("text-decoration", "none");
      }
      });
    </script>
</body>

app/views/projects/index_test.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Lists</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Personal project</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_lists.each do |project_list| %>
      <tr>
        <td><%= project_list.user_id %></td>
        <td><%= project_list.personal_project_id %></td>
        <td><%= project_list.project %></td>
        <td><%= link_to 'Show', project_list %></td>
        <td><%= link_to 'Edit', edit_project_list_path(project_list) %></td>
        <td><%= link_to 'Destroy', project_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project List', new_project_list_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<p>
  <strong>Personal project:</strong>
  <%= @project.personal_project_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @project.project %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>