config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#top"
  get "/top" => "home#top"
  get "/login" =>"home#login"

  #resources :categories
    #categoriesは管理者しか更新しないのでviewやアクションの定義の必要なし
    ##
    
  resources :habit_records, only: [:update]
    #habit_recordsのindex（habitごとのhabit_recordsの記録）はhabitのshowアクションで表示する。
  resources :users,  except: [:index]
    # indexはいらない（ユーザー一覧ののページは必要なし）
  resources :projects, except: [:new]
  get "/closed_projects" => "projects#closed"
    # "/projects"上の＋ボタンで新しいプロジェクトを作るのでnewは不要。

  resources :project_todos, only: [:create, :update, :destroy]
    # viewはいらない。管理者のみがが閲覧できればOK.
  resources :todos, except: [:new]
    # "/projects"や"/habits"上のボタンで新しいtodoを作るのでnewは不要。
  resources :habits, except: [:new]
  get "/habituation" => "habits#habituation"
    # "/habits"上の＋ボタンで新しいプロジェクトを作るのでnewは不要。


  # これを見ながらルーティングしてます。
  # https://pikawaka.com/rails/resources

  # resources　:tweetsの場合
  # get 'tweets'     => 'tweets#index'
  # get 'tweets/:id' => 'tweets#show'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id/edit' => 'tweets#edit'
  # patch 'tweets/:id'  => 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'

  # 一部だけ使うときはonlyをつける。 ex.resources :users, only: [:edit, :new]
  # 一部だけ使わないときはexceptをつける。 ex.resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :todos
end

app/models/habit.rb
class Habit < ApplicationRecord
	has_many :habit_records
	belongs_to :user
end

app/models/habit_history.rb
class HabitHistory < ApplicationRecord
end

app/models/habit_record.rb
class HabitRecord < ApplicationRecord
	belongs_to :habit
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :todos, through: :project_todos
	has_many :project_todos
end

app/models/project_todo.rb
class ProjectTodo < ApplicationRecord
	belongs_to :project
	belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user
	has_many :project_todos
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :first_name, {presence: true}
	validates :last_name, {presence: true}
	validates :user_name, {presence: true, uniqueness: true}
	validates :mail, {presence: true, uniqueness: true}


	has_many :habits
	has_many :projects
	has_many :todos


end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:user_id, :personal_todo_id, :todo, :deadline, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	render :layout  => nil
  end

  def create
  	@user = User.new(
  		first_name: params[:first_name], 
  		last_name: params[:last_name],
  		user_name: params[:user_name],
  		mail: params[:mail],
  		password: params[:password])
  	@user.save
  	redirect_to("/top")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/habit_records_helper.rb
module HabitRecordsHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/project_todos_helper.rb
module ProjectTodosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :personal_todo_id %>
    <%= form.text_field :personal_todo_id %>
  </div>

  <div class="field">
    <%= form.label :todo %>
    <%= form.text_field :todo %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Personal todo</th>
      <th>Todo</th>
      <th>Deadline</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.user_id %></td>
        <td><%= todo.personal_todo_id %></td>
        <td><%= todo.todo %></td>
        <td><%= todo.deadline %></td>
        <td><%= todo.category_id %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @todo.user_id %>
</p>

<p>
  <strong>Personal todo:</strong>
  <%= @todo.personal_todo_id %>
</p>

<p>
  <strong>Todo:</strong>
  <%= @todo.todo %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @todo.deadline %>
</p>

<p>
  <strong>Category:</strong>
  <%= @todo.category_id %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/edit.html.erb
user情報編集ページ

app/views/users/new.html.erb
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="css/base_style.css">
</head>
<body>
  <!-- わからん -->
  <a id="skippy" class="sr-only sr-only-focusable" href="#content">
    <div class="container">
      <span class="skiplink-text">Skip to main content</span>
    </div>
  </a>

  <!-- main -->
  <div class="container">
    <div class= "col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-8 offset-sm-2 col-xs-8 offset-xs-2">
      <!-- title -->
      <div class="text-center mb-4">
        <h1 class="m-3 font-weight-normal" style="font-family:Comic Sans MS;">Motiva</h1>
        <p style="font-family:Comic Sans MS;"> Let's motivate your daily life</p>
      </div>
      <div class="text-center mb-4">
        <h2 class="m-3 font-weight-normal" style="font-family:Comic Sans MS;">Create an Account</h2>
      </div>
      <!-- form -->
      <!-- 亀3/24　form_tagの追加,inputにnameタグ追加-->
      <%= form_tag("/users/") do %>
        <form class="needs-validation" novalidate>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="firstName">First name</label>
            <input type="text" name="first_name" class="form-control" id="firstName" placeholder="" value="" required>
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="lastName">Last name</label>
            <input type="text" name="last_name" class="form-control" id="lastName" placeholder="" value="" required>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="username">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">@</span>
            </div>
            <input type="text" name="user_name" class="form-control" id="username" placeholder="Username" required>
            <div class="invalid-feedback" style="width: 100%;">
              ユーザーネームを入力してください。
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="email">mail address</label>
          <input type="email" name="mail" class="form-control" id="email" placeholder="you@example.com">
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="form-label-group">
          <label for="inputPassword">password</label>
          <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        </div>
        <hr class="mb-4">
        <button type="submit" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#create_an_account" id="register_btn">Create an account</button>
        <p> If you already have an account, <a href="login_page.html">login here</a></p>
      </form>
      <% end %>



    <a href="top_page.html">開発用top</a>
    <a href="life_page.html">開発用life</a>
    <a href="work_page.html">開発用work</a>
    <a href="todo_page.html">開発用todo</a>
    </div>
  </div>
  <!-- Icons -->
  <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
  <script>
  feather.replace()
  </script>
  <!-- script -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script>
    window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script><script src="/docs/4.5/assets/js/vendor/anchor.min.js"></script>
  <script src="/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
  <script src="/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
  <script src="/docs/4.5/assets/js/src/application.js"></script>
  <script src="/docs/4.5/assets/js/src/search.js"></script>
  <script src="/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>
</body>
</html>

app/views/users/show.html.erb
ユーザー詳細ページ(マイページ的な？)