config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#top"
  get "/top" => "home#top"
  get "/login" =>"home#login"

  #resources :categories
    #categoriesは管理者しか更新しないのでviewやアクションの定義の必要なし
    ##
    
  resources :habit_records, only: [:update]
    #habit_recordsのindex（habitごとのhabit_recordsの記録）はhabitのshowアクションで表示する。
  resources :users,  except: [:index]
    # indexはいらない（ユーザー一覧ののページは必要なし）
  resources :projects, except: [:new]
  get "/closed_projects" => "projects#closed"
    # "/projects"上の＋ボタンで新しいプロジェクトを作るのでnewは不要。

  resources :project_todos, only: [:create, :update, :destroy]
    # viewはいらない。管理者のみがが閲覧できればOK.
  resources :todos, except: [:new]
    # "/projects"や"/habits"上のボタンで新しいtodoを作るのでnewは不要。
  resources :habits, except: [:new]
  get "/habituation" => "habits#habituation"
    # "/habits"上の＋ボタンで新しいプロジェクトを作るのでnewは不要。


  # これを見ながらルーティングしてます。
  # https://pikawaka.com/rails/resources

  # resources　:tweetsの場合
  # get 'tweets'     => 'tweets#index'
  # get 'tweets/:id' => 'tweets#show'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id/edit' => 'tweets#edit'
  # patch 'tweets/:id'  => 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'

  # 一部だけ使うときはonlyをつける。 ex.resources :users, only: [:edit, :new]
  # 一部だけ使わないときはexceptをつける。 ex.resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :todos
end

app/models/habit.rb
class Habit < ApplicationRecord
	has_many :habit_records
	belongs_to :user
end

app/models/habit_history.rb
class HabitHistory < ApplicationRecord
end

app/models/habit_record.rb
class HabitRecord < ApplicationRecord
	belongs_to :habit
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :todos, through: :project_todos
	has_many :project_todos
end

app/models/project_todo.rb
class ProjectTodo < ApplicationRecord
	belongs_to :project
	belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :user
	has_many :project_todos
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :first_name, {presence: true}
	validates :last_name, {presence: true}
	validates :user_name, {presence: true, uniqueness: true}
	validates :mail, {presence: true, uniqueness: true}


	has_many :habits
	has_many :projects
	has_many :todos


end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [:show, :edit, :update, :destroy]

  def habituation
  end
  
  # GET /habits
  # GET /habits.json
  def index
    @habits = Habit.all
  end

  # GET /habits/1
  # GET /habits/1.json
  def show
  end

  # GET /habits/new
  def new
    @habit = Habit.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits
  # POST /habits.json
  def create
    @habit = Habit.new(habit_params)

    respond_to do |format|
      if @habit.save
        format.html { redirect_to @habit, notice: 'Habit was successfully created.' }
        format.json { render :show, status: :created, location: @habit }
      else
        format.html { render :new }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1
  # PATCH/PUT /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to @habit, notice: 'Habit was successfully updated.' }
        format.json { render :show, status: :ok, location: @habit }
      else
        format.html { render :edit }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1
  # DELETE /habits/1.json
  def destroy
    @habit.destroy
    respond_to do |format|
      format.html { redirect_to habits_url, notice: 'Habit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      params.require(:habit).permit(:user_id, :personal_habit_id, :habit, :habituation)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:user_id, :personal_todo_id, :todo, :deadline, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	render :layout  => nil
  end

  def create
  	@user = User.new(
  		first_name: params[:first_name], 
  		last_name: params[:last_name],
  		user_name: params[:user_name],
  		mail: params[:mail],
  		password: params[:password])
  	@user.save
  	redirect_to("/top")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/habit_records_helper.rb
module HabitRecordsHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/_form.html.erb
<%= form_with(model: habit, local: true) do |form| %>
  <% if habit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(habit.errors.count, "error") %> prohibited this habit from being saved:</h2>

      <ul>
        <% habit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :personal_habit_id %>
    <%= form.text_field :personal_habit_id %>
  </div>

  <div class="field">
    <%= form.label :habit %>
    <%= form.text_field :habit %>
  </div>

  <div class="field">
    <%= form.label :habituation %>
    <%= form.number_field :habituation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/habits/edit.html.erb
<h1>Editing Habit</h1>

<%= render 'form', habit: @habit %>

<%= link_to 'Show', @habit %> |
<%= link_to 'Back', habits_path %>

app/views/habits/habituation.html.erb
habituationのリストを表示するページ

app/views/habits/index.html.erb
ここがHABITページのトップ。

<p id="notice"><%= notice %></p>

<h1>Habits</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Personal habit</th>
      <th>Habit</th>
      <th>Habituation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <tr>
        <td><%= habit.user_id %></td>
        <td><%= habit.personal_habit_id %></td>
        <td><%= habit.habit %></td>
        <td><%= habit.habituation %></td>
        <td><%= link_to 'Show', habit %></td>
        <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
        <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/habits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @habit.user_id %>
</p>

<p>
  <strong>Personal habit:</strong>
  <%= @habit.personal_habit_id %>
</p>

<p>
  <strong>Habit:</strong>
  <%= @habit.habit %>
</p>

<p>
  <strong>Habituation:</strong>
  <%= @habit.habituation %>
</p>

<%= link_to 'Edit', edit_habit_path(@habit) %> |
<%= link_to 'Back', habits_path %>